# Generated by Django 4.1.7 on 2023-03-15 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_transaction_remove_image_transfer_delete_transfer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_transfer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='child_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.childcategory'),
        ),
    ]
