# Generated by Django 4.1.7 on 2023-03-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_category_type_alter_transaction_child_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='child_category',
            new_name='category',
        ),
    ]
