# Generated by Django 4.1.7 on 2023-03-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_category_childcategory_account_name_tag_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='Счет', max_length=50, verbose_name='Название счета'),
        ),
    ]
