# Generated by Django 4.1.7 on 2023-03-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_category_user_account_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.category')),
                ('child_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.childcategory')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_transfers', to='wallet.account')),
                ('tags', models.ManyToManyField(blank=True, to='wallet.tag')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_transfers', to='wallet.account')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='transfer',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.AddField(
            model_name='image',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction'),
            preserve_default=False,
        ),
    ]
