# Generated by Django 4.1.7 on 2023-03-17 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('transfer', 'Переводы'), ('expense', 'Расходы'), ('income', 'Доходы')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='child_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wallet.category'),
        ),
        migrations.DeleteModel(
            name='ChildCategory',
        ),
    ]
